### ISSUE TITLE
Load order

### ISSUE THREAD

**Issue by SlimeDog** [jummes/MoreCompost#7]
Please add Multiverse-Core (and MultiWorld, I suppose) as a soft dependency. The following occurred on server start due to MoreCompost loading first. After MV-Core was enabled, **/morecompost reload** was successful.
```
[10:46:03] [Server thread/ERROR]: Could not call method 'public static org.bukkit.Location org.bukkit.Location.deserialize(java.util.Map)' of class org.bukkit.Location for deserialization
java.lang.IllegalArgumentException: unknown world
        at org.bukkit.Location.deserialize(Location.java:668) ~[spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeViaMethod(ConfigurationSerialization.java:85) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserialize(ConfigurationSerialization.java:127) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.serialization.ConfigurationSerialization.deserializeObject(ConfigurationSerialization.java:207) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:37) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:376) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:360) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:499) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:465) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:446) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:376) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:360) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlSeq.construct(SafeConstructor.java:499) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping2ndStep(BaseConstructor.java:465) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.SafeConstructor.constructMapping2ndStep(SafeConstructor.java:184) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructMapping(BaseConstructor.java:446) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.SafeConstructor$ConstructYamlMap.construct(SafeConstructor.java:521) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.file.YamlConstructor$ConstructCustomObject.construct(YamlConstructor.java:28) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:216) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:205) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:164) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:148) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at com.github.jummes.morecompost.libs.database.YamlDatabase.openConnection(YamlDatabase.java:48) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.libs.database.Database.<init>(Database.java:20) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.libs.database.YamlDatabase.<init>(YamlDatabase.java:33) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.libs.database.factory.DatabaseFactory.createDatabase(DatabaseFactory.java:15) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.libs.model.ModelManager.<init>(ModelManager.java:24) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.manager.CompostersManager.<init>(CompostersManager.java:20) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.core.MoreCompost.setUpData(MoreCompost.java:100) [MoreCompost-2.0.3.jar:?]
        at com.github.jummes.morecompost.core.MoreCompost.onEnable(MoreCompost.java:69) [MoreCompost-2.0.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by ZamponiMarco** [comment]
Interesting, i'm checking it now

**Comment by SlimeDog** [comment]
I unzipped the JAR, added the soft dependencies outlined above, and re-zipped the JAR, then installed it on my test server. With no other changes to the server, that resolved the issue, as expected.

**Comment by ZamponiMarco** [comment]
I know, but i want to inspect the issue a little bit deeper, cause adding a softdependency is a little bit hacky

**Comment by SlimeDog** [comment]
In what way hacky? It's how you guarantee that your plugin loads after another. It is used nearly universally (ie., most of the 157 plugins I currently test, including my own plugins), especially in multiworld situations.

**Comment by ZamponiMarco** [comment]
Let's assume we use another unknown world manager, in that way we would have the same problem, i prefer studying the problem a little bit deeper before using this solution

**Comment by SlimeDog** [comment]
There are only two prevalent world managers: Multiverse-Core and Multiworld.

**Comment by SlimeDog** [comment]
The alternative is to insert an arbitrary delay, which IS really hacky.

**Comment by ZamponiMarco** [comment]
I don't think that there is a problem in trying to search a better solution, actually.
For now, PR are always open

**Comment by SlimeDog** [comment]
True that. Always good to find better solutions.

**Comment by ZamponiMarco** [comment]
So, since it's a serious bug I'll implement your solution, but I leave this issue open to eventually develop another solution

**Comment by SlimeDog** [comment]
Works for me (and many others, potentially). Thanks.
