### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by SlimeDog** [jummes/MoreCompost#9]
Spigot 1.15.2
MoreCompost 2.0.6

On server startup
```
[20:41:13] [Server thread/ERROR]: Error occurred while enabling MoreCompost v2.0.6 (Is it up to date?)
java.lang.NullPointerException: null
	at com.github.jummes.morecompost.manager.CompostersManager.lambda$null$0(CompostersManager.java:27) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at com.github.jummes.morecompost.manager.CompostersManager.lambda$new$1(CompostersManager.java:26) ~[?:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.github.jummes.morecompost.manager.CompostersManager.<init>(CompostersManager.java:25) ~[?:?]
	at com.github.jummes.morecompost.core.MoreCompost.setUpData(MoreCompost.java:104) ~[?:?]
	at com.github.jummes.morecompost.core.MoreCompost.onEnable(MoreCompost.java:73) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by ZamponiMarco** [comment]
> Spigot 1.15.2
> MoreCompost 2.0.6
> 
> On server startup
> 
> ```
> [20:41:13] [Server thread/ERROR]: Error occurred while enabling MoreCompost v2.0.6 (Is it up to date?)
> java.lang.NullPointerException: null
> 	at com.github.jummes.morecompost.manager.CompostersManager.lambda$null$0(CompostersManager.java:27) ~[?:?]
> 	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
> 	at com.github.jummes.morecompost.manager.CompostersManager.lambda$new$1(CompostersManager.java:26) ~[?:?]
> 	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
> 	at com.github.jummes.morecompost.manager.CompostersManager.<init>(CompostersManager.java:25) ~[?:?]
> 	at com.github.jummes.morecompost.core.MoreCompost.setUpData(MoreCompost.java:104) ~[?:?]
> 	at com.github.jummes.morecompost.core.MoreCompost.onEnable(MoreCompost.java:73) ~[?:?]
> 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:432) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:464) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:378) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:457) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:274) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:784) [spigot-1.15.2.jar-2020-03-08-1937:git-Spigot-6de3d4b-fc24934]
> 	at java.lang.Thread.run(Thread.java:834) [?:?]
> ```

Hi slime, sorry for the delay but i got no notifications :(
Can i ask you for a copy of your composters.yml file? Thanks as always for the collaboration!

**Comment by SlimeDog** [comment]
composter.yml (no composters.yml) is pretty simple. Now that I look at it, I see that there are two null composters. No idea what produced them. I disabled the plugin until this is sorted. Let me know if you need more information or testing.
```
composter:
- ==: Composter
  id: playerUUID-ELIDED
  composters:
  - null
  - null
  - ==: org.bukkit.Location
    world: world_yellowdog
    x: 14499.0
    y: 64.0
    z: 1771.0
    pitch: 0.0
    yaw: 0.0
  - ==: org.bukkit.Location
    world: world_yellowdog
    x: 14499.0
    y: 64.0
    z: 1773.0
    pitch: 0.0
    yaw: 0.0
```

**Comment by ZamponiMarco** [comment]
Well, it was a bug that i actually resolved recently, but i see that there are some remainings of the bug here
I'll add something to fix such data automatically
If you just delete those nulls it will fix, tho
